<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/10 22:12:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=modern',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
